name: 发布docker镜像
on:
  push:
    # 配置触发条件，例如只在推送到master分支时触发
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新版本的Ubuntu运行器
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # 登录Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 准备 SSH Key
      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_PRIVATE_KEY" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          eval "$(ssh-agent -s)"
          ssh-add "$HOME/.ssh/id_rsa"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV

      # 构建Docker镜像
      - name: Build and push Docker image
        id: docker_build
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: redgreat/erfwong:latest
          target: builder
          cache-from: type=registry,ref=redgreat/erfwong:cache
          cache-to: type=inline
          ssh: |
            path: ~/.ssh