name: 发布docker镜像
on:
  push:
    # tags:
    #  - 'docker*'
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新版本的Ubuntu运行器
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # 登录Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建Docker镜像
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: redgreat/erfwong:latest